name: e_class
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  audioplayers: ^5.1.0
  go_router: ^13.1.0
  logging: ^1.1.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13

  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/Audio/Syllables/A.mp3
    - assets/Audio/Syllables/Al.mp3 
    - assets/Audio/Syllables/Am.mp3 
    - assets/Audio/Syllables/An.mp3 
    - assets/Audio/Syllables/Ar.mp3 
    - assets/Audio/Syllables/As.mp3 
    - assets/Audio/Syllables/Ay.mp3 
    - assets/Audio/Syllables/Ba.mp3 
    - assets/Audio/Syllables/Be.mp3 
    - assets/Audio/Syllables/Bi.mp3 
    - assets/Audio/Syllables/Bla.mp3
    - assets/Audio/Syllables/Ble.mp3
    - assets/Audio/Syllables/Bli.mp3
    - assets/Audio/Syllables/Blo.mp3
    - assets/Audio/Syllables/Blu.mp3
    - assets/Audio/Syllables/Bo.mp3
    - assets/Audio/Syllables/Bra.mp3
    - assets/Audio/Syllables/Bre.mp3
    - assets/Audio/Syllables/Bri.mp3
    - assets/Audio/Syllables/Bro.mp3
    - assets/Audio/Syllables/Bru.mp3
    - assets/Audio/Syllables/Bu.mp3
    - assets/Audio/Syllables/Ca.mp3
    - assets/Audio/Syllables/Ce.mp3
    - assets/Audio/Syllables/Cha.mp3
    - assets/Audio/Syllables/Che.mp3
    - assets/Audio/Syllables/Chi.mp3
    - assets/Audio/Syllables/Cho.mp3
    - assets/Audio/Syllables/Chu.mp3
    - assets/Audio/Syllables/Ci.mp3
    - assets/Audio/Syllables/Cla.mp3
    - assets/Audio/Syllables/Cle.mp3
    - assets/Audio/Syllables/Cli.mp3
    - assets/Audio/Syllables/Clo.mp3
    - assets/Audio/Syllables/Clu.mp3
    - assets/Audio/Syllables/Co.mp3
    - assets/Audio/Syllables/Cra.mp3
    - assets/Audio/Syllables/Cre.mp3
    - assets/Audio/Syllables/Cri.mp3
    - assets/Audio/Syllables/Cro.mp3
    - assets/Audio/Syllables/Cru.mp3
    - assets/Audio/Syllables/Cu.mp3
    - assets/Audio/Syllables/Da.mp3
    - assets/Audio/Syllables/De.mp3
    - assets/Audio/Syllables/Di.mp3
    - assets/Audio/Syllables/Do.mp3
    - assets/Audio/Syllables/Dra.mp3
    - assets/Audio/Syllables/Dre.mp3
    - assets/Audio/Syllables/Dri.mp3
    - assets/Audio/Syllables/Dro.mp3
    - assets/Audio/Syllables/Dru.mp3
    - assets/Audio/Syllables/Du.mp3
    - assets/Audio/Syllables/E.mp3
    - assets/Audio/Syllables/El.mp3
    - assets/Audio/Syllables/Em.mp3
    - assets/Audio/Syllables/En.mp3
    - assets/Audio/Syllables/Er.mp3
    - assets/Audio/Syllables/Es.mp3
    - assets/Audio/Syllables/Ey.mp3
    - assets/Audio/Syllables/Fa.mp3
    - assets/Audio/Syllables/Fe.mp3
    - assets/Audio/Syllables/Fi.mp3
    - assets/Audio/Syllables/Fla.mp3
    - assets/Audio/Syllables/Fle.mp3
    - assets/Audio/Syllables/Fli.mp3
    - assets/Audio/Syllables/Flo.mp3
    - assets/Audio/Syllables/Flu.mp3
    - assets/Audio/Syllables/Fo.mp3
    - assets/Audio/Syllables/Fra.mp3
    - assets/Audio/Syllables/Fre.mp3
    - assets/Audio/Syllables/Fri.mp3
    - assets/Audio/Syllables/Fro.mp3
    - assets/Audio/Syllables/Fru.mp3
    - assets/Audio/Syllables/Fu.mp3
    - assets/Audio/Syllables/Ga.mp3
    - assets/Audio/Syllables/Ge.mp3
    - assets/Audio/Syllables/Gi.mp3
    - assets/Audio/Syllables/Gla.mp3
    - assets/Audio/Syllables/Gle.mp3
    - assets/Audio/Syllables/Gli.mp3
    - assets/Audio/Syllables/Glo.mp3
    - assets/Audio/Syllables/Glu.mp3
    - assets/Audio/Syllables/Go.mp3
    - assets/Audio/Syllables/Gra.mp3
    - assets/Audio/Syllables/Gre.mp3
    - assets/Audio/Syllables/Gri.mp3
    - assets/Audio/Syllables/Gro.mp3
    - assets/Audio/Syllables/Gru.mp3
    - assets/Audio/Syllables/Gu.mp3
    - assets/Audio/Syllables/Gue.mp3
    - assets/Audio/Syllables/Gui.mp3
    - assets/Audio/Syllables/Ha.mp3
    - assets/Audio/Syllables/He.mp3
    - assets/Audio/Syllables/Hi.mp3
    - assets/Audio/Syllables/Ho.mp3
    - assets/Audio/Syllables/Hu.mp3
    - assets/Audio/Syllables/I.mp3
    - assets/Audio/Syllables/Ia.mp3
    - assets/Audio/Syllables/Ie.mp3
    - assets/Audio/Syllables/Il.mp3
    - assets/Audio/Syllables/Im.mp3
    - assets/Audio/Syllables/In.mp3
    - assets/Audio/Syllables/Io.mp3
    - assets/Audio/Syllables/Ir.mp3
    - assets/Audio/Syllables/Is.mp3
    - assets/Audio/Syllables/Iu.mp3
    - assets/Audio/Syllables/Ja.mp3
    - assets/Audio/Syllables/Je.mp3
    - assets/Audio/Syllables/Ji.mp3
    - assets/Audio/Syllables/Jo.mp3
    - assets/Audio/Syllables/Ju.mp3
    - assets/Audio/Syllables/Ka.mp3
    - assets/Audio/Syllables/Ke.mp3
    - assets/Audio/Syllables/Ki.mp3
    - assets/Audio/Syllables/Ko.mp3
    - assets/Audio/Syllables/Ku.mp3
    - assets/Audio/Syllables/La.mp3
    - assets/Audio/Syllables/Le.mp3
    - assets/Audio/Syllables/Li.mp3
    - assets/Audio/Syllables/lla.mp3
    - assets/Audio/Syllables/lle.mp3
    - assets/Audio/Syllables/lli.mp3
    - assets/Audio/Syllables/llo.mp3
    - assets/Audio/Syllables/llu.mp3
    - assets/Audio/Syllables/Lo.mp3
    - assets/Audio/Syllables/Lu.mp3
    - assets/Audio/Syllables/Ma.mp3
    - assets/Audio/Syllables/Me.mp3
    - assets/Audio/Syllables/Mi.mp3
    - assets/Audio/Syllables/Mo.mp3
    - assets/Audio/Syllables/Mu.mp3
    - assets/Audio/Syllables/Na.mp3
    - assets/Audio/Syllables/Ne.mp3
    - assets/Audio/Syllables/Ni.mp3
    - assets/Audio/Syllables/No.mp3
    - assets/Audio/Syllables/Nu.mp3
    - assets/Audio/Syllables/O.mp3
    - assets/Audio/Syllables/Ol.mp3
    - assets/Audio/Syllables/Om.mp3
    - assets/Audio/Syllables/On.mp3
    - assets/Audio/Syllables/Or.mp3
    - assets/Audio/Syllables/Os.mp3
    - assets/Audio/Syllables/Oy.mp3
    - assets/Audio/Syllables/Pa.mp3
    - assets/Audio/Syllables/Pe.mp3
    - assets/Audio/Syllables/Pi.mp3
    - assets/Audio/Syllables/Pla.mp3
    - assets/Audio/Syllables/Ple.mp3
    - assets/Audio/Syllables/Pli.mp3
    - assets/Audio/Syllables/Plo.mp3
    - assets/Audio/Syllables/Plu.mp3
    - assets/Audio/Syllables/Po.mp3
    - assets/Audio/Syllables/Pra.mp3
    - assets/Audio/Syllables/Pre.mp3
    - assets/Audio/Syllables/Pri.mp3
    - assets/Audio/Syllables/Pro.mp3
    - assets/Audio/Syllables/Pru.mp3
    - assets/Audio/Syllables/Pu.mp3
    - assets/Audio/Syllables/Que.mp3
    - assets/Audio/Syllables/Qui.mp3
    - assets/Audio/Syllables/Ra.mp3
    - assets/Audio/Syllables/Re.mp3
    - assets/Audio/Syllables/Ri.mp3
    - assets/Audio/Syllables/Ro.mp3
    - assets/Audio/Syllables/rra.mp3
    - assets/Audio/Syllables/rre.mp3
    - assets/Audio/Syllables/rri.mp3
    - assets/Audio/Syllables/rro.mp3
    - assets/Audio/Syllables/rru.mp3
    - assets/Audio/Syllables/Ru.mp3
    - assets/Audio/Syllables/Sa.mp3
    - assets/Audio/Syllables/Se.mp3
    - assets/Audio/Syllables/Si.mp3
    - assets/Audio/Syllables/So.mp3
    - assets/Audio/Syllables/Su.mp3
    - assets/Audio/Syllables/Ta.mp3
    - assets/Audio/Syllables/Te.mp3
    - assets/Audio/Syllables/Ti.mp3
    - assets/Audio/Syllables/Tla.mp3
    - assets/Audio/Syllables/Tle.mp3
    - assets/Audio/Syllables/Tli.mp3
    - assets/Audio/Syllables/Tlo.mp3
    - assets/Audio/Syllables/Tlu.mp3
    - assets/Audio/Syllables/To.mp3
    - assets/Audio/Syllables/Tra.mp3
    - assets/Audio/Syllables/Tre.mp3
    - assets/Audio/Syllables/Tri.mp3
    - assets/Audio/Syllables/Tro.mp3
    - assets/Audio/Syllables/Tru.mp3
    - assets/Audio/Syllables/Tu.mp3
    - assets/Audio/Syllables/U.mp3
    - assets/Audio/Syllables/Ua.mp3
    - assets/Audio/Syllables/Ue.mp3
    - assets/Audio/Syllables/Ui.mp3
    - assets/Audio/Syllables/Ul.mp3
    - assets/Audio/Syllables/Um.mp3
    - assets/Audio/Syllables/Un.mp3
    - assets/Audio/Syllables/Uo.mp3
    - assets/Audio/Syllables/Ur.mp3
    - assets/Audio/Syllables/Us.mp3
    - assets/Audio/Syllables/Uy.mp3
    - assets/Audio/Syllables/Va.mp3
    - assets/Audio/Syllables/Ve.mp3
    - assets/Audio/Syllables/Vi.mp3
    - assets/Audio/Syllables/Vo.mp3
    - assets/Audio/Syllables/Vu.mp3
    - assets/Audio/Syllables/Wa.mp3
    - assets/Audio/Syllables/We.mp3
    - assets/Audio/Syllables/Wi.mp3
    - assets/Audio/Syllables/Wo.mp3
    - assets/Audio/Syllables/Wu.mp3
    - assets/Audio/Syllables/Xa.mp3
    - assets/Audio/Syllables/Xe.mp3
    - assets/Audio/Syllables/Xi.mp3
    - assets/Audio/Syllables/Xo.mp3
    - assets/Audio/Syllables/Xu.mp3
    - assets/Audio/Syllables/Ya.mp3
    - assets/Audio/Syllables/Ye.mp3
    - assets/Audio/Syllables/Yi.mp3
    - assets/Audio/Syllables/Yo.mp3
    - assets/Audio/Syllables/Yu.mp3
    - assets/Audio/Syllables/Za.mp3
    - assets/Audio/Syllables/Ze.mp3
    - assets/Audio/Syllables/Zi.mp3
    - assets/Audio/Syllables/Zo.mp3
    - assets/Audio/Syllables/Zu.mp3
    - assets/Audio/Syllables/Ña.mp3
    - assets/Audio/Syllables/Ñe.mp3
    - assets/Audio/Syllables/Ñi.mp3
    - assets/Audio/Syllables/Ño.mp3
    - assets/Audio/Syllables/Ñu.mp3
    - assets/Audio/win.mp3
    - assets/menu_background.jpg
    - assets/settings_background.jpg
    - assets/game_background.jpg
    - assets/play_button.png
    - assets/play_sound_button.png
    - assets/settings_button.png
    - assets/arrow_button_back.png
    - assets/disable.png
    - assets/enable.png
    - assets/note.png
    - assets/star.gif
    - assets/star_2.gif
    - assets/white/lives_1.png
    - assets/white/lives_2.png
    - assets/white/lives_3.png
    - assets/white/points_0.png
    - assets/white/points_1.png
    - assets/white/points_2.png
    - assets/white/points_3.png
    - assets/white/points_4.png
    - assets/white/points_5.png

  fonts:
    - family: Heirany Slight
      fonts:
        - asset: assets/Heirany_Slight.ttf
    - family: Fifth Grader
      fonts:
        - asset: assets/Fifth-Grader.ttf
    - family: Ginthul
      fonts:
        - asset: assets/Ginthul.ttf
