name: e_class
description: "An interactive app for learning sounds in spanish."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:

  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that the package needs in order to work.
dependencies:

  flutter:

    sdk: flutter
  
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.6 # Adds the Cupertino Icons font to the application.
  device_preview: ^1.1.0
  gif_view: ^0.4.4
  go_router: ^14.2.1
  provider: ^6.0.2
  shared_preferences: ^2.0.13

dev_dependencies:

  flutter_test:

    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/Images/icon.png"
  min_sdk_android: 21

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with the application.
  uses-material-design: true

  assets:

    - assets/Audio/Music/
    - assets/Audio/SFX/
    - assets/Audio/Syllables/
    - assets/Images/Decoration/Background/
    - assets/Images/Decoration/Animated/
    - assets/Images/UI/
    - assets/Images/UI/points/

  fonts:

    - family: Ginthul
      fonts:

        - asset: assets/Ginthul.ttf
