const names = {
  'a': ['avión', 'amor', 'anillo', 'abeja', 'águila'],
  'e': ['elefante', 'estrella', 'edificio', 'erizo', 'enano'],
  'i': ['igual', 'iglesia', 'indio', 'iguana', 'imán'],
  'o': ['oveja', 'oído', 'oso', 'oruga', 'ocho'],
  'u': ['unicornio', 'universo', 'uva', 'uno', 'uniforme'],
  'm': ['mamá', 'mesa', 'microbio', 'moneda', 'muñeca'],
  'p': ['pato', 'pera', 'piña', 'pollo', 'puño'],
  'l': ['lápiz', 'león', 'limón', 'loro', 'luna'],
  's': ['sapo', 'semáforo', 'silla', 'sol', 'suma'],
  't': ['taza', 'telaraña', 'tiburón', 'tomate', 'tucán'],
  'n': ['naranja', 'nena', 'nido', 'noche', 'nube'],
  'd': ['dado', 'dedo', 'dinosaurio', 'dona', 'duda'],
  'c': ['casa', 'cebolla', 'cinco', 'conejo', 'cuchara'],
  'qu': ['queso', 'quinientos'],
  'b': ['barril', 'bebé', 'biberón', 'bote', 'búho'],
  'v': ['vaca', 'vela', 'violín', 'vocales', 'vuelo'],
  'rr': ['jarra', 'torre', 'perrito', 'carro', 'serrucho'],
  'r': ['ratero', 'reparador', 'riñón', 'roca', 'ruleta'],
  'f': ['familia', 'feliz', 'fila', 'foco ', 'fuego'],
  'j': ['jamón', 'jeringa', 'jirafa', 'joroba', 'juguete'],
  'g': ['gato', 'gemelas', 'girasol', 'gota', 'guante'],
  'gu': ['guerrero', 'guitarra'],
  'ñ': ['ñame', 'bañera', 'meñique', 'ñoquis', 'ñu'],
  'h': ['hacha', 'helado', 'hilo', 'hoja', 'hueso'],
  'ch': ['chaqueta', 'chelo', 'chivo', 'choza', 'chupón'],
  'll': ['llaves', 'galletas', 'pollito', 'llorar', 'lluvia'],
  'w': ['waterpolo', 'web', 'kiwi', 'wok', 'wushu'],
  'y': ['yate', 'yegua', 'yin', 'yoyo', 'yuca'],
  'z': ['zapato', 'zepelín', 'zíper', 'zorro', 'zumo'],
  'k': ['karaoke', 'kebab', 'kilo', 'koala', 'kufiya'],
  'pl': ['plátano', 'plegaria', 'pliegue', 'plomero', 'pluma'],
  'bl': ['blanco', 'sable', 'blindado', 'bloc', 'blusa'],
  'cl': ['clavo', 'clérigo', 'clínica', 'clóset', 'clueca'],
  'fl': ['flaco', 'flecha', 'flirteo', 'flotador', 'fluido'],
  'gl': ['gladiador', 'ingle', 'jeroglífico', 'globo', 'iglú'],
  'pr': ['prado', 'premio', 'prisionero', 'profesor', 'prueba'],
  'br': ['brazo', 'brebaje', 'brincar', 'brocha', 'bruja'],
  'cr': ['cráneo', 'crema', 'criada', 'cronómetro', 'cruz'],
  'fr': ['fragancia', 'fresa', 'frijoles', 'frotar', 'fruta'],
  'tr': ['tractor', 'tren', 'trigo', 'trotar', 'trucha'],
  'gr': ['grama', 'cangrejo', 'grillo', 'ogro', 'grúa'],
  'dr': ['dragón', 'padre', 'cocodrilo', 'dromedario', 'druida'],
  'vl': ['alpaca', 'elfo', 'mil', 'olfato', 'ultrasonido'],
  'vn': ['ángel', 'enfermo', 'inflar', 'once', 'untar'],
  'vs': ['astronauta', 'escalera', 'isla', 'ostra', 'uslero'],
  'x': ['hexágono', 'boxeo', 'xilófono', 'saxofón', 'sexual'],
  'vr': ['arcoíris', 'erguir', 'reír', 'orquídea', 'urna'],
  'vm': ['ambulancia', 'embarazo', 'impresora', 'ombligo', 'tumbado'],
  'iv': ['piano', 'pie', 'piojo', 'viuda'],
  'uv': ['lengua', 'juez', 'buitre', 'monstruo'],
  'vy': ['Uruguay', 'buey', 'morrocoy', 'cucuy']
};
